In [3]:
import pandas as pd
import numpy as np

In [4]:
np.random.randint(120, 150, size=10)

array([126, 143, 147, 125, 138, 146, 144, 147, 142, 136], dtype=int32)

In [5]:
np.random.randint(120, 150, size=(10, 5))

array([[136, 126, 140, 128, 148],
       [128, 141, 135, 149, 122],
       [124, 125, 148, 128, 147],
       [138, 124, 141, 138, 146],
       [133, 128, 147, 122, 147],
       [124, 136, 129, 149, 123],
       [122, 121, 149, 128, 126],
       [147, 135, 127, 141, 144],
       [142, 136, 133, 145, 131],
       [122, 147, 138, 140, 129]], dtype=int32)

In [6]:
np.round(np.random.rand(4, 5)*100,2)

array([[67.39, 30.02, 94.36,  5.17, 97.9 ],
       [67.37, 54.9 , 87.37, 72.39, 35.39],
       [97.85, 50.51,  9.72, 19.85, 85.6 ],
       [ 1.98, 19.67, 51.72, 40.39,  5.83]])

In [7]:
np_arr = np.random.choice(['Delhi', "Pune", "Mumbai"], size=(3, 5))
np_arr

array([['Delhi', 'Delhi', 'Pune', 'Mumbai', 'Delhi'],
       ['Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai'],
       ['Mumbai', 'Mumbai', 'Delhi', 'Delhi', 'Pune']], dtype='<U6')

In [8]:
data_1 = pd.DataFrame( np_arr, columns=['col_1', 'col_2', 'col_3', 'col_4', 'col_5'], index=['a','b', 2] )
data_1

    col_1   col_2  col_3   col_4   col_5
a   Delhi   Delhi   Pune  Mumbai   Delhi
b  Mumbai   Delhi   Pune   Delhi  Mumbai
2  Mumbai  Mumbai  Delhi   Delhi    Pune

In [9]:
# using these "random" functions to generate data!

In [10]:
states = np.random.choice(['DL', 'HR', 'MH', 'TN'], size=12)
age = np.random.randint(18, 29, size=12)
marks = np.round(np.random.rand(12)*1000, 3)
# marks
marital_status = np.random.choice((True, False), size=(12))

days = np.random.randint(1, 30, size=(12))
# months = np.random.choice(['Jan', 'Feb', "Mar", 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'], size=12)
months = np.random.randint(1, 13, size=12)
years = np.random.choice([2024, 2025, 2026], size=12)

emp_id = [ "emp_"+str(np.random.randint(150, 500, 1)[0]) for i in range(0, 12) ]
emp_id

['emp_362',
 'emp_317',
 'emp_399',
 'emp_195',
 'emp_462',
 'emp_233',
 'emp_441',
 'emp_364',
 'emp_346',
 'emp_245',
 'emp_309',
 'emp_192']

In [11]:
# try -1 : to get dates!
(f"{days}-{months}-{years}")

'[ 2  9 10 21 15 16 13 15 20 13  4 14]-[ 1  7 11  7 12  7  6  7  8  8  1  5]-[2026 2025 2026 2026 2026 2024 2026 2026 2024 2026 2024 2024]'

In [12]:
# try-2 : to get dates
# str(days)+"/"+months+"/"+str(years)

In [13]:
# try-3 : to get dates using loop -> success

dates = np.array([ str(days[i])+"-"+str(months[i])+"-"+str(years[i]) for i in range(0, len(days)) ])
print(type(dates))
print()
print(dates)
print()

<class 'numpy.ndarray'>

['2-1-2026' '9-7-2025' '10-11-2026' '21-7-2026' '15-12-2026' '16-7-2024'
 '13-6-2026' '15-7-2026' '20-8-2024' '13-8-2026' '4-1-2024' '14-5-2024']

In [14]:
dates.dtype

dtype('<U10')

In [15]:
# arr_dt = dates.astype("datetime64[D]")

In [16]:
# converting dates to proper type using pandas and converting back to numpy!

dates = pd.to_datetime(dates, dayfirst=True).to_numpy(dtype="datetime64[D]")

In [17]:
dates

array(['2026-01-02', '2025-07-09', '2026-11-10', '2026-07-21',
       '2026-12-15', '2024-07-16', '2026-06-13', '2026-07-15',
       '2024-08-20', '2026-08-13', '2024-01-04', '2024-05-14'],
      dtype='datetime64[D]')

In [18]:
# create a dataframe from all individual sources!

df = pd.DataFrame({
    "emp_id":emp_id,
    "states":states,
    "marks":marks,
    "marital_status":marital_status,
    "joining_dates":dates
})
df

     emp_id states    marks  marital_status joining_dates
0   emp_362     MH  473.758           False    2026-01-02
1   emp_317     TN   76.824           False    2025-07-09
2   emp_399     TN  130.835            True    2026-11-10
3   emp_195     MH  271.440           False    2026-07-21
4   emp_462     DL  958.866            True    2026-12-15
5   emp_233     HR  299.132           False    2024-07-16
6   emp_441     DL  196.944            True    2026-06-13
7   emp_364     TN  590.082            True    2026-07-15
8   emp_346     MH  848.863           False    2024-08-20
9   emp_245     TN  854.547            True    2026-08-13
10  emp_309     TN   73.375            True    2024-01-04
11  emp_192     TN  998.401           False    2024-05-14

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   emp_id          12 non-null     object
 1   states          12 non-null     object
 2   marks           12 non-null     float64
 3   marital_status  12 non-null     bool
 4   joining_dates   12 non-null     datetime64[s]
dtypes: bool(1), datetime64[s](1), float64(1), object(2)
memory usage: 528.0+ bytes

In [20]:
# extracting detailes from date cols.

df['joining_month'] = df['joining_dates'].dt.month_name()
df['joining_year'] = df['joining_dates'].dt.year

df['joining_day_of_week'] = df['joining_dates'].dt.dayofweek
df['joining_day_name'] = df['joining_dates'].dt.day_name()

# np.where -> to get indexes of elements based on condition, to use as conditional statement as well!
# df['joining_day_type'] = np.where(
#     df['joining_dates'].dt.dayofweek >= 5, "Weekend", "Weekday"
# )

# df[['joining_dates']].applymap(lambda x: "Weekend" if x.dayofweek >= 5 else "Weekday" )
# Correct way → apply on Series
df['joining_day_type'] = df['joining_dates'].apply(
    lambda x: "Weekend" if x.dayofweek >= 5 else "Weekday"
)

In [21]:
df

,emp_id,states,marks,marital_status,joining_dates,joining_month,joining_year,joining_day_of_week,joining_day_name,joining_day_type
0,emp_362,MH,473.758,False,2026-01-02,January,2026,4,Friday,Weekday
1,emp_317,TN,76.824,False,2025-07-09,July,2025,2,Wednesday,Weekday
2,emp_399,TN,130.835,True,2026-11-10,November,2026,1,Tuesday,Weekday
3,emp_195,MH,271.440,False,2026-07-21,July,2026,1,Tuesday,Weekday
4,emp_462,DL,958.866,True,2026-12-15,December,2026,1,Tuesday,Weekday
5,emp_233,HR,299.132,False,2024-07-16,July,2024,1,Tuesday,Weekday
6,emp_441,DL,196.944,True,2026-06-13,June,2026,5,Saturday,Weekend
7,emp_364,TN,590.082,True,2026-07-15,July,2026,2,Wednesday,Weekday
8,emp_346,MH,848.863,False,2024-08-20,August,2024,1,Tuesday,Weekday
9,emp_245,TN,854.547,True,2026-08-13,August,2026,3,Thursday,Weekday
10,emp_309,TN,73.375,True,2024-01-04,January,2024,3,Thursday,Weekday
11,emp_192,TN,998.401,False,2024-05-14,May,2024,1,Tuesday,Weekday

In [22]:
# in marks, break on basis of . and check does left ad right part are above 200 , if yes count those!

# conversion -> split -> divide into cols. -> type conversion -> comparison -> sum (row-wise) -> list conversion
(df['marks'].astype(str).str.split(".", expand=True).astype(float) > 200).sum(axis=1).to_list()

[2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 2]

In [23]:
df['marks'].values

array([473.758,  76.824, 130.835, 271.44 , 958.866, 299.132, 196.944,
       590.082, 848.863, 854.547,  73.375, 998.401])

In [24]:
# in marks how many values are above 3 in each cell?
(df['marks'].astype(str).str.split("", expand=True).reset_index().apply(pd.to_numeric, errors='coerce') > 3).sum(axis=1).to_list()

[5, 4, 2, 3, 7, 3, 6, 4, 6, 7, 4, 5]